
# Site settings
title: Droll Blog
email: noonmonster10@gmail.com
description: Java, Blog, Git, Spring 
url: drollh.github.io

# User setting
owner: Droll
email: noonmonster10@gmail.com
facebook_username:
twitter_username:
github_username: drollh
address:
  - line:
  - line:
telephone:
copyright:

# API settings
google_api_key:

# Build settings
gems: [jekyll-paginate]

markdown: kramdown
# toc_levels: 1..2
